apiVersion: v1
kind: PersistentVolume
metadata:
  name: simplybyte-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/my-data
