apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:  # A mandatory rule; the pod will not be scheduled unless the condition is satisfied.
          #preferredDuringSchedulingIgnoredDuringExecution → A soft preference; the scheduler tries to satisfy the condition, but will still schedule the pod elsewhere if necessary.
          - labelSelector:
              matchExpressions:
              - key: app            # we are giving label of redis.yml
                operator: In
                values:
                - redis
            topologyKey: kubernetes.io/hostname
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command: ["sleep", "3600"]


