# created by me, so first try required. then you can try this yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - redis
              topologyKey: kubernetes.io/hostname
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - sleep
        - "3600"
