apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simplybyte-mysql
  labels:
    app: mysql
spec:
  serviceName: mysql       # name of the headless service, as its a stateful application we need to use this service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD      # In env variable section of docker page, you will get it
              valueFrom:
                secretKeyRef:
                  name: mysql-secret         # name of the secret
                  key: mysql-root-password   # in secret file we can see this key
            - name: MYSQL_DATABASE          # In env variable section of docker page, you will get it. also for this env, we given value directly.
              value: simplybyte
          volumeMounts:
            - name: mysql-data              # Name of the volume
              mountPath: /var/lib/mysql     # Data stored in mysql will be stored in this location only
  volumeClaimTemplates:                     # It will create a PVC/PV automatically
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
